productionList = [
    Production("prog ->  'Shader' String { shader_body }",
               'p1',
               N.prog,
               ('Shader', T.String, T.LBrace, N.shader_body, T.RBrace, )),
    Production("shader_body ->  props subshr",
               'p2',
               N.shader_body,
               (N.props, N.subshr, )),
    Production("props ->  'Properties' { props_body }",
               'p3',
               N.props,
               ('Properties', T.LBrace, N.props_body, T.RBrace, )),
    Production("props -> ",
               'p4',
               N.props,
               ()),
    Production("props_body ->  prop_stm props_body",
               'p5',
               N.props_body,
               (N.prop_stm, N.props_body, )),
    Production("props_body -> ",
               'p6',
               N.props_body,
               ()),
    Production("prop_stm ->  ID ( String , ReservedWord ) = prop_init",
               'p7',
               N.prop_stm,
               (T.ID, T.LParen, T.String, T.Comma, T.ReservedWord, T.RParen, T.Assign, N.prop_init, )),
    Production("prop_init ->  Number",
               'p8',
               N.prop_init,
               (T.Number, )),
    Production("prop_init ->  String { }",
               'p9',
               N.prop_init,
               (T.String, T.LBrace, T.RBrace, )),
    Production("prop_init ->  ( Number , Number , Number , Number )",
               'p10',
               N.prop_init,
               (T.LParen, T.Number, T.Comma, T.Number, T.Comma, T.Number, T.Comma, T.Number, T.RParen, )),
    Production("subshr ->  'SubShader' { subshr_body }",
               'p11',
               N.subshr,
               ('SubShader', T.LBrace, N.subshr_body, T.RBrace, )),
    Production("subshr_body ->  tags cmds passes",
               'p12',
               N.subshr_body,
               (N.tags, N.cmds, N.passes, )),
    Production("tags ->  'Tags' { tags_body }",
               'p13',
               N.tags,
               ('Tags', T.LBrace, N.tags_body, T.RBrace, )),
    Production("tags_body ->  tag_smt tags_body",
               'p14',
               N.tags_body,
               (N.tag_smt, N.tags_body, )),
    Production("tags_body -> ",
               'p15',
               N.tags_body,
               ()),
    Production("tag_smt ->  String = String",
               'p16',
               N.tag_smt,
               (T.String, T.Assign, T.String, )),
    Production("cmds ->  cmd_stm cmds",
               'p17',
               N.cmds,
               (N.cmd_stm, N.cmds, )),
    Production("cmds -> ",
               'p18',
               N.cmds,
               ()),
    Production("cmd_stm ->  ReservedWord ids",
               'p19',
               N.cmd_stm,
               (T.ReservedWord, N.ids, )),
    Production("ids ->  ID ids",
               'p20',
               N.ids,
               (T.ID, N.ids, )),
    Production("ids -> ",
               'p21',
               N.ids,
               ()),
    Production("passes ->  shr_pass passes",
               'p22',
               N.passes,
               (N.shr_pass, N.passes, )),
    Production("passes -> ",
               'p23',
               N.passes,
               ()),
    Production("shr_pass ->  'Pass' { pass_body }",
               'p24',
               N.shr_pass,
               ('Pass', T.LBrace, N.pass_body, T.RBrace, )),
    Production("pass_body ->  'CGPROGRAM' cg_prog 'ENDCG'",
               'p25',
               N.pass_body,
               ('CGPROGRAM', N.cg_prog, 'ENDCG', )),
    Production("cg_prog ->  cg_stms",
               'p26',
               N.cg_prog,
               (N.cg_stms, )),
    Production("cg_stms ->  cg_stm cg_stms",
               'p27',
               N.cg_stms,
               (N.cg_stm, N.cg_stms, )),
    Production("cg_stms -> ",
               'p28',
               N.cg_stms,
               ()),
    Production("cg_stm ->  preprocessing_stm",
               'p29',
               N.cg_stm,
               (N.preprocessing_stm, )),
    Production("preprocessing_stm ->  pp_if_stm",
               'p30',
               N.preprocessing_stm,
               (N.pp_if_stm, )),
    Production("preprocessing_stm ->  pp_cmd",
               'p31',
               N.preprocessing_stm,
               (N.pp_cmd, )),
    Production("pp_if_stm ->  # 'if' ID",
               'p32',
               N.pp_if_stm,
               (T.Pound, 'if', T.ID, )),
    Production("pp_if_stm ->  # 'ifdef' ID",
               'p33',
               N.pp_if_stm,
               (T.Pound, 'ifdef', T.ID, )),
    Production("pp_if_stm ->  # 'idndef' ID",
               'p34',
               N.pp_if_stm,
               (T.Pound, 'idndef', T.ID, )),
    Production("pp_if_stm ->  # 'elif' ID",
               'p35',
               N.pp_if_stm,
               (T.Pound, 'elif', T.ID, )),
    Production("pp_if_stm ->  # 'else'",
               'p36',
               N.pp_if_stm,
               (T.Pound, 'else', )),
    Production("pp_if_stm ->  # 'endif'",
               'p37',
               N.pp_if_stm,
               (T.Pound, 'endif', )),
    Production("pp_cmd ->  # 'include' String",
               'p38',
               N.pp_cmd,
               (T.Pound, 'include', T.String, )),
    Production("pp_cmd ->  # 'pragma' ids",
               'p39',
               N.pp_cmd,
               (T.Pound, 'pragma', N.ids, )),
]
