productionList = [
    Production("prog ->  'Shader' String { shader_body }",
               'p1',
               N.prog,
               ('Shader', T.String, T.LBrace, N.shader_body, T.RBrace, )),
    Production("shader_body ->  props subshr",
               'p2',
               N.shader_body,
               (N.props, N.subshr, )),
    Production("props ->  'Properties' { props_body }",
               'p3',
               N.props,
               ('Properties', T.LBrace, N.props_body, T.RBrace, )),
    Production("props -> ",
               'p4',
               N.props,
               ()),
    Production("props_body ->  prop_stm props_body",
               'p5',
               N.props_body,
               (N.prop_stm, N.props_body, )),
    Production("props_body -> ",
               'p6',
               N.props_body,
               ()),
    Production("prop_stm ->  ID ( String , ReservedWord ) = prop_init",
               'p7',
               N.prop_stm,
               (T.ID, T.LParen, T.String, T.Comma, T.ReservedWord, T.RParen, T.Assign, N.prop_init, )),
    Production("prop_init ->  Number",
               'p8',
               N.prop_init,
               (T.Number, )),
    Production("prop_init ->  String { }",
               'p9',
               N.prop_init,
               (T.String, T.LBrace, T.RBrace, )),
    Production("prop_init ->  ( Number , Number , Number , Number )",
               'p10',
               N.prop_init,
               (T.LParen, T.Number, T.Comma, T.Number, T.Comma, T.Number, T.Comma, T.Number, T.RParen, )),
    Production("subshr ->  'SubShader' { subshr_body }",
               'p11',
               N.subshr,
               ('SubShader', T.LBrace, N.subshr_body, T.RBrace, )),
    Production("subshr_body ->  tags directives pass",
               'p12',
               N.subshr_body,
               (N.tags, N.directives, N.pass, )),
    Production("tags ->  'Tags' { tags_body }",
               'p13',
               N.tags,
               ('Tags', T.LBrace, N.tags_body, T.RBrace, )),
    Production("tags_body ->  tag_smt tags_body",
               'p14',
               N.tags_body,
               (N.tag_smt, N.tags_body, )),
    Production("tags_body -> ",
               'p15',
               N.tags_body,
               ()),
    Production("tag_smt ->  String = String",
               'p16',
               N.tag_smt,
               (T.String, T.Assign, T.String, )),
    Production("directives ->  directive_name ID directives",
               'p17',
               N.directives,
               (N.directive_name, T.ID, N.directives, )),
    Production("directive_name ->  Lighting",
               'p18',
               N.directive_name,
               (T.Lighting, )),
    Production("directive_name ->  Cull",
               'p19',
               N.directive_name,
               (T.Cull, )),
    Production("directive_name ->  ZTest",
               'p20',
               N.directive_name,
               (T.ZTest, )),
    Production("directive_name ->  ZWrite",
               'p21',
               N.directive_name,
               (T.ZWrite, )),
    Production("directive_name ->  Blend",
               'p22',
               N.directive_name,
               (T.Blend, )),
    Production("pass ->  Pass { pass_body }",
               'p23',
               N.pass,
               (T.Pass, T.LBrace, N.pass_body, T.RBrace, )),
    Production("pass_body ->  CGPROGRAM",
               'p24',
               N.pass_body,
               (T.CGPROGRAM, )),
]
